### ISSUE TITLE
scoring

### ISSUE THREAD

**Issue by lottybrand** [lottybrand22/lottysBartlett#14]
At some point we need to record participants' score as they go along. This will simply be one point for the "Rwer" and 0 points for the "Wwer", 0 points if they skip, and 0 points if everyone chooses to copy. 
Would be nice to display as percentage correct - or perhaps even a ranking/scoreboard system. 

One thing to think about- will we display their overall score so far, or their individual score (ie their own score when they hadn't copied someone else?) or do we just include all that info?

**Comment by thomasmorgan** [comment]
If "score" is stored as a property you can easily get % correct simply by dividing score by the current question number -1 (all players are on the same question as each other)

Whether you want to display their overall score or just their score on questions where they used asocial information is up to you. I'd say its hard to see how an observer could tell the historical causes of a person's success so the overall score is more realistic, but if your goal is to provide a measure of asocial ability (realism be damned) then I'd go for the asocial only score (though if you do this calculating the % correct becomes harder because you'll also need to check how many questions they even tried to answer with asocial information)

**Comment by lottybrand** [comment]
I've had a first attempt at this by trying to copy what you did with the "copy" property2 in submit_response but it isn't quite working. 
I also noticed that I lazily made all the submit-a buttons the Wwer (wrong answer) and submit-b the right answer (Rwer - our super secret code). 
So, for now I was going to just have property3 be "correct" each time submit-b is submitted, and then count up the number of "corrects" per player_id...? somehow?  But, before going down this route, is there a way of randomising the position of the submit-a and submit-b buttons, without having to randomise which one is Rwer and Wwer? Otherwise the correct answer is always going to be displayed on the right...

**Comment by thomasmorgan** [comment]
To randomize buttons, try the following. Currently we add labels to buttons as follows:
```
        $("#submit-a").html(Wwer);
        $("#submit-b").html(Rwer);
```

to randomize do this instead:
```
        if (Math.random() < 0.5) {
            $("#submit-a").html(Wwer);
            $("#submit-b").html(Rwer);
        } else {
            $("#submit-b").html(Wwer);
            $("#submit-a").html(Rwer);
        }
```

For scoring, it's easier if you set property3 to 1 for correct and 0 for wrong, that way you are dealing with ints straight off the bat (though they will turn into strings in the table anyway.

To add this to your code try modifying submit_response as follows:

```
//not entirely sure what this does
submit_response = function(response, copy=false) {
    score = (response == Rwer)*1
    dallinger.createInfo(my_node_id, {
        contents: response,
        info_type: "Info",
        property1: number,
        property2: copy,
        property3: score
    }).done(function (resp) {
        most_recent_question = number;
        setTimeout(function() {
            get_transmissions();
        }, 1000);
    });
}
```

**Comment by lottybrand** [comment]
This works and records each correct (individual) response in the property3 column (it doesn't count copied responses but I'm fine with that for now). 
We want to calculate a running score, and also a total score per player_id. 
Could this be something along the lines of: 

> total_score = 0
> for i in player_id:
> 	if property3 == 1:
> 		total_score +=1 
 ?

**Comment by thomasmorgan** [comment]
because we are saving score as a number you can just do:

```
total_score += int(property3)
```

**Comment by lottybrand** [comment]
but that wouldn't give a total score for each player..? would it?

**Comment by lottybrand** [comment]
So what I meant to say in the above is that at the moment score is being recorded as 0 or 1 for each INFO, rather than each node, and the only way to link it to each node is through origin_id, which doesn't correspond to player_id or participant_id (although I think it is simply always participant_id + 1 as it is counting the source too). 
So, we want each node to have property1 as player_id (which we already have), property2 as number of times copied (which we have), and property 3 as total score for round 1 (not yet calculated).

**Comment by lottybrand** [comment]
So actually, participant_id corresponds to player_id if you click "begin" in the same order that you clicked the "Accept hit" button. But even when that is the case, the code I just pushed doesn't do what I want it to, but you can probably see what I was trying to get it to do...
Aside from that, we should probably make sure participant_id and player_id match up anyway, for this reason (but also, origin_id and player_id never match up either, because of the source, which I think could be tricky when trying to figure out who copied who using the info table...?)

**Comment by thomasmorgan** [comment]
The easiest way to have property3 of node be their total score is have the `info_post_request` function add the score of the info added to the score of the node. It's a little tricky because you don't want to do this for all infos, just those that correspond to a participant making a decision (e.g. "Jack Vettriano") or the info created by copying someone else (not the "copy someone else" info, but the "Jack Vettriano" info created due to copying).

**Comment by lottybrand** [comment]
Yeah I see what you mean, but, at the moment the score function doesn't actually increment score for a copied answer anyway, but I'm fine with that for now, as ideally it will be "individual score" (at least to begin with) rather than individual and copied score. 
Eventually we'll want each player_id's score to be continuously updating, as well as having access to a total score from the first round. But for now, I'd just like to record each player's total score for round 1 (on their individual answers only). 
This probably isn't how you'd go about doing it, but I don't know why what I've just committed doesn't work. Is it a simple python syntax thing (I notice you've got str(int) in front of your stuff in the above method, do I need that for my part too?), or is it that Dallinger can't increment the info in the nodes table based on what's in the infos table?

**Comment by thomasmorgan** [comment]
"I'd just like to record each player's total score for round 1 (on their individual answers only)"
OK, this is quite straightforward then. I think round is stored as property 5 (?) of the info, so only increment score if info.property 5 == 1.

"I notice you've got str(int) in front of your stuff in the above method, do I need that for my part too?"
Probably. Everything (even numbers) get stored in the property columns as Strings because they are defined as columns of Strings (unlike id which is defined as a column of ints). So you need to use int() to turn the value into a number before you can add to it etc. I use str() to convert it back into a string afterwards, but you probably can get away without that as it will do it automatically when you try to insert an int into a String column.

"I don't know why what I've just committed doesn't work"
I'll give it a look

**Comment by thomasmorgan** [comment]
@lottybrand22 ok, changes pushed. You code almost worked, it was mostly just missing int() in a few places. I've fixed it a simplified it a little.
